# Generated by Django 3.2.9 on 2021-11-20 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20211120_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
